version: "3"
volumes:
  postgis-data:
  sessions-data:
services:
  main:
    image: main
    networks:
      - default
    volumes:
      - ./logs:/app/app-log
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - films-bd
      - sessions
    restart: on-failure
  films-bd:
    image: postgres:16
    expose:
      - "5432"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=films
      - POSTGRES_DB=films
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  sessions:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - sessions-data:/data
    restart: always
networks:
  default:
    driver: bridge